In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [11]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)

In [12]:
print(v1)

[ 2.13904064e-02 -7.39799812e-02  1.42067927e-03  2.13816669e-02
  2.45113149e-02  3.15582938e-02 -1.10839717e-01 -1.05017461e-01
 -6.18259013e-02 -6.42311573e-03  3.72399599e-03  9.06393304e-02
 -9.49936919e-03  6.53976873e-02  1.10946447e-02 -2.10097190e-02
 -3.35125439e-02 -4.31677178e-02  9.96348634e-03  1.41969668e-02
 -6.40415475e-02 -7.04179564e-03 -7.91187882e-02  5.80030754e-02
  1.30208058e-03  4.19733115e-03  5.70979007e-02  6.39447793e-02
  2.49902979e-02 -3.95876542e-02 -3.79506610e-02  2.70394329e-02
  1.79423466e-02  1.72272418e-02  3.43311131e-02  9.29058064e-03
  5.86054996e-02 -4.97789495e-02 -5.05370460e-03  4.34328578e-02
 -1.56623106e-02 -2.97534652e-02 -5.13326470e-03  5.13414927e-02
  6.16064109e-03  6.86980560e-02 -1.29505387e-02 -5.61938547e-02
 -1.08265085e-02  5.96683957e-02  5.29939942e-02 -3.42755243e-02
 -4.15273979e-02 -5.43295778e-02 -7.14876829e-03  1.28990725e-01
  2.09546294e-02  1.25907138e-02 -1.04924902e-01  1.57250781e-02
 -7.83413202e-02 -2.66572

In [14]:
v1.shape

(384,)

In [15]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [16]:
print(dv)

[-4.81206737e-02 -1.29942089e-01 -4.86810366e-03  1.37495538e-02
 -8.51099752e-03  6.97841272e-02 -7.55665964e-03  4.09571752e-02
 -1.02165602e-01 -3.45050655e-02  2.85521764e-02 -5.81430495e-02
 -1.85113493e-02 -3.17839012e-02  5.29631041e-02  3.96292806e-02
 -9.84595809e-03 -6.45324141e-02  7.05097765e-02 -6.39589280e-02
 -3.55156884e-02 -1.75490454e-02 -3.58401611e-02  5.50857105e-04
  3.38445418e-02  2.91762911e-02  3.24278362e-02 -5.64803556e-03
  8.42592940e-02  5.90306260e-02  2.08772775e-02 -5.44832088e-03
  2.98403557e-02  1.30820675e-02  6.36077300e-02 -3.06394044e-02
  6.28459752e-02 -1.69217605e-02 -4.65758331e-02 -5.13762236e-02
 -3.81560810e-02 -7.01197162e-02 -9.55517888e-02  5.01640290e-02
  8.57913867e-03  1.19207567e-02 -1.40597252e-02 -7.98978005e-03
 -3.44238393e-02 -2.34269686e-02  2.89466046e-02  2.68904716e-02
 -4.87409122e-02 -1.32924933e-02 -8.13224539e-02  4.34518419e-02
  6.60785884e-02 -4.70225699e-02 -2.56785192e-02 -9.07628164e-02
 -1.41222104e-02 -3.70062

In [17]:
v1.dot(dv)

np.float32(0.323324)

In [18]:
q2 = "How to install Docker on Windows?"
v2 = model.encode(q2)

In [19]:
v2.dot(dv)

np.float32(0.019730467)

In [23]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [24]:
from src.ingestion import load_faq_data

documents = load_faq_data()
print(f"Loaded {len(documents)} documents")

Loaded 1350 documents


In [25]:
documents[10]

{'id': '316180784f',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: How many hours per week am I expected to spend on this course?',
 'answer': 'It depends on your background and previous experience with modules. It is expected to require about 5 - 15 hours per week.\n\nYou can also calculate it yourself using [this data](https://github.com/DataTalksClub/zoomcamp-analytics/tree/main/data/de-zoomcamp-2023) and then update this answer.'}

In [26]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [27]:
texts[10]

'Course: How many hours per week am I expected to spend on this course? It depends on your background and previous experience with modules. It is expected to require about 5 - 15 hours per week.\n\nYou can also calculate it yourself using [this data](https://github.com/DataTalksClub/zoomcamp-analytics/tree/main/data/de-zoomcamp-2023) and then update this answer.'

In [28]:
from tqdm.auto import tqdm

In [29]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [ ]:
import numpy as np
X = np.array(vectors) #turning into matrix for matrix vector multiplication 

In [32]:
print(X)

[[-0.02670622 -0.12245756  0.01594419 ... -0.00230645 -0.11218392
  -0.02365552]
 [-0.01099556 -0.11074746 -0.02536935 ...  0.09022225 -0.02697366
   0.01975673]
 [-0.08896549 -0.0612818   0.00775604 ...  0.04059709  0.00479281
  -0.02745942]
 ...
 [-0.03652925  0.01415435 -0.06838642 ...  0.04316787  0.08105537
  -0.02148628]
 [-0.1309159  -0.06990597 -0.00931879 ... -0.00044343 -0.01285731
   0.01426924]
 [-0.07984778  0.01926991  0.02544983 ... -0.0336802  -0.01884021
   0.05837058]]


In [33]:
len(texts)

1350

In [34]:
query = "Can I still join the course after the start date?"
v_query = model.encode(query)

In [35]:
scores = X.dot(v_query)

In [36]:
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(2), np.float32(0.762941))

In [80]:
documents[idx]

{'id': '3f1424af17',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

In [ ]:
top5 = np.argsort(scores)[-5:]

In [82]:
print(top5)

[  7 538 907 625   2]


In [84]:
scores[top5]

array([0.56009996, 0.6536313 , 0.71921325, 0.7579372 , 0.762941  ],
      dtype=float32)

In [92]:
top5 = top5[::-1]
scores[top5]

array([0.762941  , 0.7579372 , 0.71921325, 0.6536313 , 0.56009996],
      dtype=float32)

In [93]:
for idx in top5:
    print(scores[idx])
    print(documents[idx])
    print()

0.762941
{'id': '3f1424af17', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

0.7579372
{'id': '2d8b16c2a0', 'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute."}

0.71921325
{'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related

In [94]:
from minsearch import VectorSearch

In [95]:

vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [96]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vindex.search(query_vector, num_results=5)

In [97]:
print(results)

[{'id': '74eb249bbf', 'course': 'llm-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'I just discovered the course. Can I still join?', 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}, {'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'The course has already started. Can I still join it?', 'answer': 'Yes, you can. Even though you missed the start date, you can register for the course. You won’t be able to submit some of the homeworks, but you can still take part in the course.\n\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'}, {'id': '2d8b16c2a0', 'course': 'mlops-zoomcamp', 'section': 'General Course-Relat

In [98]:
results[0]

{'id': '74eb249bbf',
 'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

In [99]:
results = vindex.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [100]:
from dotenv import load_dotenv
load_dotenv

<function dotenv.main.load_dotenv(dotenv_path: Union[str, ForwardRef('os.PathLike[str]'), NoneType] = None, stream: Optional[IO[str]] = None, verbose: bool = False, override: bool = False, interpolate: bool = True, encoding: Optional[str] = 'utf-8') -> bool>

In [101]:
from groq import Groq
client = Groq(
    api_key= os.getenv("GROQ_API_KEY")
)

In [102]:
from src.ingestion import load_faq_data, build_index
documents = load_faq_data()
index = build_index(documents)

In [103]:
from src.rag_helper import RAGBase

assistant = RAGBase(
    index=index,
    llm_client=client,
)

In [104]:

class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

In [105]:
vector_assistant = RAGVector(
    embedder=model,
    index=vindex,
    llm_client=client,
)

In [106]:
vector_assistant.rag("whats the program about, is there any project that we need to do, and what about certificate?")

'Based on the provided information, here\'s an answer to your questions:\n\n**What\'s the program about?**\nUnfortunately, the information about the program is not provided in the given context. However, I can try to give a general answer based on the provided details. Based on the questions and answers, it appears that the program is a online course that likely involves learning and working on a project, with a focus on peer review and collaboration. The course seems to be designed to provide some sort of certification upon completion.\n\n**Is there any project that we need to do?**\nYes, there is a Capstone Project that you need to submit. The project will be evaluated by your peers, and you will also be responsible for grading the projects from three fellow students.\n\n**What about the certificate?**\nTo receive a certificate, you need to submit your Capstone Project while the course is still accepting submissions. Even if you miss the project deadline or the initial homework, you 

In [107]:
from sqlitesearch import VectorSearchIndex

vs_index = VectorSearchIndex(
    keyword_fields=["course"],
    mode="ivf",
    db_path="faq_vectors2.db"
)

In [108]:
'''
sqlitesearch supports three ANN modes:

lsh (default): up to 100K vectors, random hyperplane projections
ivf: 10K-500K vectors, K-means clustering
hnsw: 10K-1M+ vectors, proximity graph (highest recall)
For our small dataset, lsh is fine. All modes use two-phase search: approximate candidate retrieval, then exact cosine similarity reranking.'''

'\nsqlitesearch supports three ANN modes:\n\nlsh (default): up to 100K vectors, random hyperplane projections\nivf: 10K-500K vectors, K-means clustering\nhnsw: 10K-1M+ vectors, proximity graph (highest recall)\nFor our small dataset, lsh is fine. All modes use two-phase search: approximate candidate retrieval, then exact cosine similarity reranking.'

In [109]:
vs_index.fit(vectors, documents)

In [110]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vs_index.search(query_vector, num_results=5)

In [111]:
results

[{'id': '74eb249bbf',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'},
 {'id': '41aabbd7c5',
  'course': 'machine-learning-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'The course has already started. Can I still join it?',
  'answer': 'Yes, you can. Even though you missed the start date, you can register for the course. You won’t be able to submit some of the homeworks, but you can still take part in the course.\n\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'},
 {'id': '2d8b16c2a0',
  'course': 'mlops-zoomcamp',
  'section':

In [112]:
vs_index.close()